export const journalPrompts = [
    "What is one thing you did recently that makes you proud? How can you build on it?",
    "Which challenge are you avoiding, and what tiny first step could you take today?",
    "Who relied on you this week, and how did you show up for them?",
    "When did you feel most confident lately? What contributed to that feeling?",
    "What strengths do others see in you that you sometimes overlook?",
    "How would your 10-year-ago self react to where you are now?",
    "What have you learned from a recent setback that makes you stronger?",
    "What does being a good man mean to you today versus five years ago?",
    "Which boundary do you need to protect to feel more energized?",
    "What small act of courage can you commit to in the next 24 hours?",
    "When did you last feel deep gratitude, and how can you recreate that today?",
    "What part of your routine most supports your mental health? What would improve it?",
    "Who inspires you to be better, and what trait of theirs can you practice today?",
    "If today were your best day this month, what would make it so?",
    "What would you tell a close friend who is struggling the way you are right now?",
    "Where do you feel the most at peace, and how can you bring a piece of that into today?",
    "What is a recurring negative thought you can reframe with evidence from your life?",
    "Which promise to yourself do you want to keep today?",
    "How have you shown resilience this year? List three examples.",
    "What do you want to thank your body for today?",
    "What is one responsibility you've been carrying well lately that deserves recognition?",
    "If fear wasn't a factor, what decision would you make today?",
    "What is something you've outgrown that you're still holding onto?",
    "When do you feel most like your authentic self?",
    "What lesson has life been trying to teach you recently?",
    "What area of your life feels neglected, and what is one way to invest in it today?",
    "What does success look like for you right now—not five years from now, but today?",
    "What are you tolerating that is quietly draining your energy?",
    "What is one habit that future-you will thank you for building?",
    "How do you typically respond to stress, and is that response serving you?",
    "What is a belief about yourself that no longer feels true?",
    "Who in your life deserves more appreciation from you?",
    "What challenge are you facing that could become a source of growth?",
    "What is one thing you can forgive yourself for today?",
    "When was the last time you surprised yourself in a positive way?",
    "What would a healthier version of you do differently this week?",
    "What conversation have you been avoiding, and why?",
    "What are three things going right in your life that you rarely acknowledge?",
    "How do you want people to feel after spending time with you?",
    "What personal value have you honored recently?",
    "Where are you seeking control over things you cannot control?",
    "What goal matters most to you right now, and why?",
    "How would you spend today if you knew it would be remembered forever?",
    "What distraction is stealing time from what matters most?",
    "What does strength mean to you beyond physical ability?",
    "What have you been meaning to start, and what is stopping you?",
    "What is one difficult truth you've been avoiding?",
    "When do you feel most connected to the people you care about?",
    "What kind of example are you setting through your daily actions?",
    "What does your inner critic say most often, and how would you respond to it as a friend?",
    "What is one thing you can let go of that no longer serves your growth?",
    "What accomplishment are you minimizing that deserves celebration?",
    "What would make this week feel meaningful when you look back on it?",
    "What does balance look like in your life right now?",
    "What is something you've survived that once felt impossible?",
    "How do you want to be remembered by the people closest to you?",
    "What area of your life could benefit from more discipline?",
    "What are you grateful for that money cannot buy?",
    "What emotion have you been pushing away instead of processing?",
    "What is one way you've become wiser in the past year?",
    "If you trusted yourself completely, what would you do next?",
    "What does a fulfilling life look like to you?",
    "What are you doing today that aligns with the person you want to become?",
    "What would happen if you stopped waiting for the perfect time?",
    "What relationship in your life deserves more attention?",
    "What challenge has shaped your character the most?",
    "How have your priorities changed over the last few years?",
    "What is one thing you need to hear right now?",
    "What does self-respect look like in your actions today?",
    "What are you building that will still matter a year from now?",
    "What is one lesson from your childhood that you want to pass on to your children?",
    "How do you want your family to describe you in ten years?",
    "What family tradition would you like to start or strengthen?",
    "When was the last time you were fully present with your family without distractions?",
    "What quality do you hope your children learn by watching you?",
    "How did your parents shape the way you show love today?",
    "What is one memory you want your family to remember about this season of life?",
    "How do you show your family they are a priority?",
    "What does being a great father mean to you?",
    "What family value is most important for you to uphold?",
    "When did you last express appreciation to a family member?",
    "What is one way you can be more emotionally available for your family this week?",
    "How do you want your children to handle adversity, and are you modeling that behavior?",
    "What family relationship deserves more of your attention right now?",
    "What is one thing your family does well together?",
    "What kind of home environment are you helping create each day?",
    "How do you want your children to remember your presence, not just your achievements?",
    "What sacrifices have you made for your family that you're proud of?",
    "What is one conversation you've been meaning to have with a family member?",
    "How can you create more meaningful moments with your family this month?",
    "What is a trait from your father or father figure that you admire?",
    "What is a trait from your father or father figure that you want to improve upon?",
    "How do you respond when your family needs you during stressful moments?",
    "What does unconditional love look like in your family?",
    "What family memory still brings you joy today?",
    "How can you better support your partner as a parent or family member?",
    "What example are you setting when it comes to responsibility and integrity?",
    "How do you balance providing for your family with being present for them?",
    "What is one thing you wish your family knew about you?",
    "How can you strengthen trust within your family?",
    "What does quality time mean to your family, and are you creating enough of it?",
    "What family challenge has brought you closer together?",
    "How do you show affection and encouragement to the people you love?",
    "What is one way your family has helped you become a better man?",
    "What values do you hope future generations of your family carry forward?",
    "How would your children describe your character today?",
    "What is one thing you can do this week to make your family feel more loved?",
    "How do you handle conflict within your family, and what could improve?",
    "What family tradition from your upbringing would you like to preserve?",
    "What legacy do you hope to leave for your family beyond financial success?",
    "How do you demonstrate patience with the people you love most?",
    "What moment with your family are you most grateful for this year?",
    "How can you create a stronger sense of belonging within your home?",
    "What life lesson do you hope your children learn from watching you overcome challenges?",
    "How do you want your family to feel when they are around you?",
    "What is one way you can lead your family through example rather than words?",
    "What role does forgiveness play in your family relationships?",
    "What is something your family needs from you right now?",
    "How are you investing in your family's future today?",
    "What kind of legacy are you building through your daily actions at home?"
];

function seededIndex(seed: string, max: number) {
    let hash = 0;
    for (let i = 0; i < seed.length; i++) {
        hash = (hash * 31 + seed.charCodeAt(i)) >>> 0;
    }
    return hash % max;
}

export function getDailyJournalPrompt(date: string) {
    const idx = seededIndex(date, journalPrompts.length);
    return journalPrompts[idx];
}
